language: r
pandoc_version: 1.19.2.1

r_packages:
  - devtools

r_github_packages:
  - nulib/kuyper-stat202


#env:
#  global:
#    - secure: A_LONG_ENCRYPTED_STRING

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files